name: Deploy Astro Site to GitHub Pages

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

permissions:
  contents: write # Changed to write to allow committing new images
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "20"
      - name: Install dependencies
        run: npm install
      - name: Compile Amazon Image Enrichment Script
        run: npm run compile-enrichment # Compile the TypeScript script
      - name: Run Amazon Image Enrichment Script
        run: npm run enrich-amazon # Execute the compiled JavaScript script
      - name: Commit new images and map
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "feat: Add new Amazon product images and map from enrichment"
          branch: ${{ github.head_ref || github.ref_name }} # Commit to the current branch (PR or push)
          file_pattern: 'public/images/enrichment/*.jpg src/data/amazonImageMap.json' # Commit new images and the map
      - name: Build site
        run: npm run build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build-and-deploy
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
